import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      'node_modules/',
      'dist/',
      '**/dist/',
      'public/',
      'drizzle/',
      'data/',
      // Cargo build output for the desktop shell. tauri-codegen writes the embedded
      // web bundle back out here as .js, which eslint would otherwise try to parse.
      '**/target/',
      // Generated by tauri-build from tauri.conf.json on every build.
      'apps/desktop/src-tauri/gen/',
      // Expo prebuild/runtime output. Source under apps/mobile/src remains linted.
      'apps/mobile/.expo/',
      'apps/mobile/android/',
      'apps/mobile/ios/',
      '*.config.ts',
      '*.config.js',
      '**/*.mjs',
    ],
  },

  // Base JS recommended
  js.configs.recommended,

  // TypeScript recommended
  ...tseslint.configs.recommended,

  // React Hooks
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // Project-specific rules
  {
    rules: {
      // Relax rules for practical development
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'no-constant-condition': 'off',
      'no-useless-escape': 'warn',
      'prefer-const': 'warn',
      'no-unused-private-class-members': 'off',
      'no-new-native-nonconstructor': 'off',
      'preserve-caught-error': 'off',
    },
  },

  // Prettier (must be last — disables conflicting formatting rules)
  prettier,
);
