#!/usr/bin/env python3
"""
Generate Android vector drawables for the app's semantic icons.

Android navigation-bar items (expo-router `Stack.Toolbar` → Compose `IconButton`)
need an image source — SF Symbol names render nothing there. This extracts the
Material Symbol glyphs that src/ui/core.tsx maps every `IconName` to, from the
same font expo-symbols draws in-content icons with (Material Symbols Outlined,
weight 400), so toolbar and content icons are identical.

  python3 scripts/android-icons.py      # from apps/mobile; needs fontTools

Writes assets/icons/android/<material_name>.xml (24dp, viewport = the font's
960-unit icon grid) and the `IconName` → drawable table in
src/ui/toolbar-icon.android.ts. Re-run after adding an icon to core.tsx.
"""
import glob
import json
import os
import re
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
OUT = os.path.join(APP, 'assets', 'icons', 'android')

fonts = glob.glob(os.path.join(APP, 'node_modules', '.pnpm', '@expo-google-fonts+material-symbols@*', 'node_modules',
                               '@expo-google-fonts', 'material-symbols', '400Regular', 'MaterialSymbols_400Regular.ttf'))
if not fonts:
    sys.exit('MaterialSymbols_400Regular.ttf not found — install dependencies first')
font = TTFont(fonts[0])
GRID = font['head'].unitsPerEm  # 960: the icon box is [0, GRID] on both axes
cmap = font.getBestCmap()
glyphs = font.getGlyphSet()
codepoints = json.load(open(os.path.join(APP, 'node_modules', 'expo-symbols', 'build', 'android', 'symbols.json')))

# The semantic icon table: `name: ['sf.name', 'material_name'],`
core = open(os.path.join(APP, 'src', 'ui', 'core.tsx'), encoding='utf-8').read()
pairs = re.findall(r"^\s+(\w+): \['[^']+', '([a-z0-9_]+)'\],", core, re.M)
names = sorted({md for _, md in pairs})

os.makedirs(OUT, exist_ok=True)
for name in names:
    glyph = cmap.get(codepoints[name])
    pen = SVGPathPen(glyphs)
    # font units are y-up from the baseline; drawables are y-down from the top
    glyphs[glyph].draw(TransformPen(pen, (1, 0, 0, -1, 0, GRID)))
    xml = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- Material Symbols Outlined 400 "{name}" — generated by scripts/android-icons.py -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="24dp" android:height="24dp"\n'
        f'    android:viewportWidth="{GRID}" android:viewportHeight="{GRID}">\n'
        f'  <path android:fillColor="#FF000000" android:pathData="{pen.getCommands()}"/>\n'
        '</vector>\n'
    )
    with open(os.path.join(OUT, f'{name}.xml'), 'w') as fh:
        fh.write(xml)
# src/ui/toolbar-icon.android.ts — the table between the SOURCES markers
ts_path = os.path.join(APP, 'src', 'ui', 'toolbar-icon.android.ts')
ts = open(ts_path, encoding='utf-8').read()
start = ts.index('const SOURCES')
end = ts.index('};', start) + 2
table = '\n'.join(f"  {n}: require('../../assets/icons/android/{md}.xml')," for n, md in pairs)
ts = ts[:start] + 'const SOURCES: Record<IconName, ImageSourcePropType> = {\n' + table + '\n};' + ts[end:]
open(ts_path, 'w', encoding='utf-8').write(ts)
print(f'{len(names)} icons → {os.path.relpath(OUT, APP)}; {len(pairs)} names → src/ui/toolbar-icon.android.ts')
