/**
 * Drizzle schema — Cloud Agent Runtime tables (PostgreSQL).
 *
 * Tables: agent_workspaces, agent_runs, agent_run_events, agent_artifacts,
 * agent_run_approvals, agent_run_outbox
 *
 * A cloud-agent run is one disposable container executing a Pi coding-agent
 * session in the owner's persistent workspace (design:
 * docs/specs/20260731-cloud-agent-runtime.md). These rows are the SOURCE OF
 * TRUTH for the controller state machine and the UI: `agent_runs` drives the
 * per-user queue and the boot sweep after an api restart, `agent_run_events`
 * is the step-level timeline the web replays (the UI never reads the sandbox
 * filesystem), and `agent_artifacts` records deliverables persisted to COS —
 * the sandbox is never the only copy of anything worth keeping.
 * `relay_client_id` is a logical reference to `api_clients` (no FK): the
 * per-run relay key is disabled at end-of-run, but audit rows outlive it.
 */

import { pgTable, serial, text, integer, bigint, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';
import type { AgentRunStatus as WireAgentRunStatus } from '@greenhouse/types/cloud-agent';
import { users } from './user.js';

// ─── agent_workspaces ────────────────────────────────────

export const agentWorkspaces = pgTable(
  'agent_workspaces',
  {
    id: serial('id').primaryKey(),
    user_id: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    /** archived = tarball on COS (cos_archive_key), local dir reclaimed. */
    status: text('status', { enum: ['active', 'archived'] })
      .notNull()
      .default('active'),
    /** Last measured on-disk size (bytes); node_modules etc. included. */
    disk_bytes: bigint('disk_bytes', { mode: 'number' }).notNull().default(0),
    cos_archive_key: text('cos_archive_key'),
    last_used_at: timestamp('last_used_at', { withTimezone: true, mode: 'string' }).notNull(),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [index('idx_agent_workspaces_user').on(table.user_id)],
);

// ─── agent_runs ──────────────────────────────────────────

export const agentRuns = pgTable(
  'agent_runs',
  {
    /** `car_<hex>` — generated by the service, also the workspace dir name. */
    id: text('id').primaryKey(),
    user_id: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    workspace_id: integer('workspace_id')
      .notNull()
      .references(() => agentWorkspaces.id, { onDelete: 'cascade' }),
    // TS-level enum only (pg `text` emits no CHECK), so adding a status needs no migration.
    status: text('status', { enum: ['queued', 'starting', 'running', 'completed', 'failed', 'canceled'] })
      .notNull()
      .default('queued'),
    /** Stable identity of a Mission Dispatch card; null for standalone runs. */
    dispatch_id: text('dispatch_id'),
    title: text('title').notNull(),
    /** Exact user-authored instruction, never decorated for the runner. */
    original_prompt: text('original_prompt').notNull(),
    /** Runner-facing prompt, including structured attachment guidance. */
    prompt: text('prompt').notNull(),
    /** Frozen attachment/input metadata JSON for audit and replay. */
    input_manifest: text('input_manifest').notNull().default('[]'),
    /** Model registry id (config/models.yaml), e.g. 'flash'. */
    model: text('model').notNull(),
    /** Registry id the runner downgrades to on upstream 429/quota exhaustion. */
    fallback_model: text('fallback_model'),
    /** Docker container id once started (boot sweep reconciles against it). */
    container_id: text('container_id'),
    /** Per-run relay api_clients.id (logical relation, no FK — see header). */
    relay_client_id: text('relay_client_id'),
    /**
     * Chat session this run converses through (channel='mission'; logical
     * relation, no FK — deleting the conversation keeps the run audit).
     */
    session_id: text('session_id'),
    /** Wall-clock budget; also the task token TTL. */
    max_wall_ms: integer('max_wall_ms').notNull().default(7_200_000),
    /** LLM request budget (provider quota is deployment-shared). */
    max_requests: integer('max_requests').notNull().default(300),
    used_requests: integer('used_requests').notNull().default(0),
    input_tokens: integer('input_tokens').notNull().default(0),
    output_tokens: integer('output_tokens').notNull().default(0),
    result_summary: text('result_summary'),
    /** Stable machine-readable failure reason rendered by the web. */
    failure_code: text('failure_code'),
    error: text('error'),
    /** Object-storage key of the archived runner journal. */
    journal_storage_key: text('journal_storage_key'),
    queued_at: timestamp('queued_at', { withTimezone: true, mode: 'string' }).notNull(),
    started_at: timestamp('started_at', { withTimezone: true, mode: 'string' }),
    ended_at: timestamp('ended_at', { withTimezone: true, mode: 'string' }),
    /** Terminal cleanup/outbox/journal reconciliation completed. */
    settled_at: timestamp('settled_at', { withTimezone: true, mode: 'string' }),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    index('idx_agent_runs_user').on(table.user_id),
    index('idx_agent_runs_status').on(table.status),
    index('idx_agent_runs_workspace').on(table.workspace_id),
    index('idx_agent_runs_session').on(table.session_id),
    uniqueIndex('uq_agent_runs_dispatch').on(table.dispatch_id),
  ],
);

// ─── agent_run_events ────────────────────────────────────

export const agentRunEvents = pgTable(
  'agent_run_events',
  {
    id: serial('id').primaryKey(),
    run_id: text('run_id')
      .notNull()
      .references(() => agentRuns.id, { onDelete: 'cascade' }),
    /**
     * Runner-assigned, per-run monotonic. The unique index makes event
     * ingestion idempotent (the runner retries pushes after api restarts);
     * the web polls `seq > after` for incremental replay.
     */
    seq: integer('seq').notNull(),
    type: text('type').notNull(),
    /** Exact step-level event payload JSON; permanent and never auto-truncated. */
    payload: text('payload').notNull().default('{}'),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    uniqueIndex('uq_agent_run_events_run_seq').on(table.run_id, table.seq),
    index('idx_agent_run_events_run').on(table.run_id),
  ],
);

// ─── agent_artifacts ─────────────────────────────────────

export const agentArtifacts = pgTable(
  'agent_artifacts',
  {
    id: serial('id').primaryKey(),
    run_id: text('run_id')
      .notNull()
      .references(() => agentRuns.id, { onDelete: 'cascade' }),
    /** Path relative to /workspace/artifacts inside the container. */
    path: text('path').notNull(),
    size_bytes: integer('size_bytes').notNull(),
    content_type: text('content_type').notNull().default('application/octet-stream'),
    sha256: text('sha256').notNull(),
    /** Upload storage key (COS or local fallback — storage/uploads.ts). */
    storage_key: text('storage_key').notNull(),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [index('idx_agent_artifacts_run').on(table.run_id)],
);

// ─── agent_run_approvals ────────────────────────────────

export const agentRunApprovals = pgTable(
  'agent_run_approvals',
  {
    /** `caa_<hex>` — one exact, single-use mutation approval lease. */
    id: text('id').primaryKey(),
    run_id: text('run_id')
      .notNull()
      .references(() => agentRuns.id, { onDelete: 'cascade' }),
    user_id: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tool_id: text('tool_id').notNull(),
    action: text('action'),
    input_hash: text('input_hash').notNull(),
    input_json: text('input_json').notNull(),
    status: text('status', { enum: ['pending', 'approved', 'denied', 'consumed', 'expired'] })
      .notNull()
      .default('pending'),
    expires_at: timestamp('expires_at', { withTimezone: true, mode: 'string' }).notNull(),
    decided_by: text('decided_by').references(() => users.id, { onDelete: 'set null' }),
    decided_at: timestamp('decided_at', { withTimezone: true, mode: 'string' }),
    consumed_at: timestamp('consumed_at', { withTimezone: true, mode: 'string' }),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    index('idx_agent_run_approvals_run_status').on(table.run_id, table.status),
    index('idx_agent_run_approvals_user_status').on(table.user_id, table.status),
  ],
);

// ─── agent_run_outbox ───────────────────────────────────

export const agentRunOutbox = pgTable(
  'agent_run_outbox',
  {
    /** One frozen outcome per run. */
    run_id: text('run_id')
      .primaryKey()
      .references(() => agentRuns.id, { onDelete: 'cascade' }),
    session_id: text('session_id').notNull(),
    message_id: text('message_id').notNull(),
    content: text('content').notNull(),
    status: text('status', { enum: ['pending', 'delivered'] })
      .notNull()
      .default('pending'),
    attempts: integer('attempts').notNull().default(0),
    last_error: text('last_error'),
    delivered_at: timestamp('delivered_at', { withTimezone: true, mode: 'string' }),
    created_at: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull(),
    updated_at: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [index('idx_agent_run_outbox_status').on(table.status, table.created_at)],
);

// ─── Row types (inferred — schema is the single source of truth) ──

export type AgentWorkspaceRow = typeof agentWorkspaces.$inferSelect;
export type AgentWorkspaceStatus = AgentWorkspaceRow['status'];
export type AgentRunRow = typeof agentRuns.$inferSelect;
export type AgentRunStatus = AgentRunRow['status'];
export type AgentRunEventRow = typeof agentRunEvents.$inferSelect;
export type AgentArtifactRow = typeof agentArtifacts.$inferSelect;
export type AgentRunApprovalRow = typeof agentRunApprovals.$inferSelect;
export type AgentRunApprovalStatus = AgentRunApprovalRow['status'];
export type AgentRunOutboxRow = typeof agentRunOutbox.$inferSelect;

/**
 * The column enum and the wire contract (`@greenhouse/types/cloud-agent`) must stay
 * the same set: the api pushes this status over WS and the web renders it. This
 * assertion is bidirectional, so adding a status on either side alone fails
 * typecheck instead of quietly reaching the browser as an unhandled value.
 */
type _AssertRunStatusParity = [
  AgentRunStatus extends WireAgentRunStatus ? true : never,
  WireAgentRunStatus extends AgentRunStatus ? true : never,
];
