#!/usr/bin/env python3
"""Build Haven assets from one SVG and the bundled Nunito source.

Requires Python fonttools[woff], Pillow, rsvg-convert.
Run from any directory: python3 scripts/build-brand-assets.py
"""
from pathlib import Path
import base64
import json
import shutil
import subprocess
import xml.etree.ElementTree as ET

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'packages/ui/src/assets/greenhouse-mark.svg'
FONTS = ROOT / 'packages/ui/src/assets/fonts'
NS = {'s': 'http://www.w3.org/2000/svg'}
paths = [{k: node.attrib[k] for k in ('id', 'd', 'fill')} for node in ET.parse(SOURCE).findall('s:path', NS)]


def write(path, content):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return target


def svg_markup(*, light=False, mono=False):
    house = ' '.join(p['d'] for p in paths if p['id'] != 'seed')
    seed = next(p for p in paths if p['id'] == 'seed')
    house_fill = '#FFFFFF' if mono else '#D7EFDD' if light else paths[0]['fill']
    seed_fill = '#FFFFFF' if mono else seed['fill']
    return f'<path d="{house}" fill="{house_fill}"/><path d="{seed["d"]}" fill="{seed_fill}"/>'



def svg(body, box='0 0 224 224'):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}" role="img" aria-label="Greenhouse"><title>Greenhouse</title>{body}</svg>\n'


def raster(source, target, size):
    target = ROOT / target
    target.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(['rsvg-convert', '-w', str(size), '-h', str(size), str(source), '-o', str(target)], check=True)


# Browser fonts: variable normal/italic. Native fonts: real named static instances.
for name, output in [('Nunito-Variable.ttf', 'nunito-variable.woff2'), ('Nunito-Italic-Variable.ttf', 'nunito-italic-variable.woff2')]:
    font = TTFont(FONTS / name)
    font.flavor = 'woff2'
    font.save(FONTS / output)
native_fonts = ROOT / 'apps/mobile/assets/fonts'
native_fonts.mkdir(parents=True, exist_ok=True)
for weight, style in [(400, 'Regular'), (500, 'Medium'), (600, 'SemiBold'), (700, 'Bold')]:
    font = instantiateVariableFont(TTFont(FONTS / 'Nunito-Variable.ttf'), {'wght': weight}, inplace=True)
    # Variable source names say ExtraLight. Give each static face its real identity.
    names = {1: 'Nunito', 2: style, 4: f'Nunito {style}', 6: f'Nunito-{style}', 16: 'Nunito', 17: style}
    for record in font['name'].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    font.save(native_fonts / f'Nunito-{style}.ttf')
shutil.copy(FONTS / 'OFL.txt', native_fonts / 'OFL.txt')
for folder in [ROOT / 'docs/fonts']:
    shutil.copy(FONTS / 'nunito-variable.woff2', folder / 'nunito-variable.woff2')
    shutil.copy(FONTS / 'OFL.txt', folder / 'Nunito-OFL.txt')

# Diagram WebViews run outside RN's font registry. Embed the same small WOFF2
# so inline and full-screen diagrams work without an additional font request.
web_font = '@font-face{font-family:Nunito;font-style:normal;font-weight:200 1000;src:url(data:font/woff2;base64,' + base64.b64encode((FONTS / 'nunito-variable.woff2').read_bytes()).decode() + ') format("woff2");}'
write('apps/mobile/src/ui/brand-web-font.generated.ts', '// Generated by scripts/build-brand-assets.py from the bundled SIL OFL Nunito font.\nexport const NUNITO_WEB_FONT_CSS = ' + json.dumps(web_font) + ';\n')

# Both renderer copies are generated from the canonical SVG (Mobile is standalone).
generated = '// Generated by scripts/build-brand-assets.py; edit packages/ui/src/assets/greenhouse-mark.svg.\n'
generated += 'export const GREENHOUSE_PATHS = ' + json.dumps(paths, indent=2) + ' as const;\n'
write('packages/ui/src/components/brand/paths.generated.ts', generated)
write('apps/mobile/src/ui/brand.generated.ts', generated)
write('logos/greenhouse-mark.svg', svg(svg_markup()))

icon = svg('<rect width="280" height="280" rx="62" fill="#235D4D"/>' + '<g transform="translate(28 28)">' + svg_markup(light=True) + '</g>', '0 0 280 280')
icon_path = write('logos/greenhouse-app-icon.svg', icon)
for target in ['apps/web/public/favicon.svg', 'apps/browser/assets/icon.svg', 'docs/favicon.svg']:
    write(target, icon)
raster(icon_path, 'logos/greenhouse-app-icon.png', 1024)
for target, size in [('apps/web/public/icon-192.png', 192), ('apps/web/public/icon-512.png', 512), ('apps/web/public/apple-touch-icon.png', 180), ('docs/apple-touch-icon.png', 180)]:
    raster(icon_path, target, size)
for size in [16, 32, 48, 128, 512]:
    raster(icon_path, f'apps/browser/public/icons/icon-{size}.png', size)
Image.open(ROOT / 'logos/greenhouse-app-icon.png').save(ROOT / 'apps/web/public/favicon.ico', sizes=[(16,16),(32,32),(48,48)])

# iOS icons are opaque, square: the OS applies its own corner mask.
mobile_icon = write('logos/greenhouse-mobile-icon.svg', icon.replace('rx="62"', 'rx="0"'))
raster(mobile_icon, 'apps/mobile/assets/icon.png', 1024)
adaptive = write('logos/greenhouse-adaptive-icon.svg', svg('<g transform="translate(100 100)">' + svg_markup(light=True) + '</g>', '0 0 424 424'))
raster(adaptive, 'apps/mobile/assets/adaptive-icon.png', 1024)

# Desktop sizes are part of the existing Tauri bundle contract.
desktop = ROOT / 'apps/desktop/src-tauri/icons'
for target in desktop.glob('*.png'):
    if target.name == 'menubar-template.png':
        template = write('logos/greenhouse-template.svg', svg(svg_markup(light=True, mono=True)))
        raster(template, target.relative_to(ROOT), 44)
    else:
        with Image.open(target) as image:
            size = image.width
        raster(icon_path, target.relative_to(ROOT), size)
image = Image.open(ROOT / 'logos/greenhouse-app-icon.png')
image.save(desktop / 'icon.ico', sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)])
image.save(desktop / 'icon.icns')

# Outlined Nunito wordmark: no font installed on the recipient's machine is required.
font = instantiateVariableFont(TTFont(FONTS / 'Nunito-Variable.ttf'), {'wght': 700}, inplace=True)
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
pen = SVGPathPen(glyphs)
x = 0
for char in 'Greenhouse':
    glyph = glyphs[cmap[ord(char)]]
    glyph.draw(TransformPen(pen, (1, 0, 0, 1, x, 0)))
    x += glyph.width
scale = 0.041
width = round(111 + x * scale + 8, 2)
wordmark = svg('<g transform="translate(0 0) scale(.44)">' + svg_markup() + '</g>' + f'<path transform="translate(108 65) scale({scale} {-scale})" fill="#235D4D" d="{pen.getCommands()}"/>', f'0 0 {width} 100')
wordmark_path = write('logos/greenhouse-logo.svg', wordmark)
subprocess.run(['rsvg-convert', '-w', '1440', str(wordmark_path), '-o', str(ROOT / 'logos/greenhouse-logo.png')], check=True)
print('Built Haven marks, all client icons, Nunito web/native fonts and outlined wordmark.')
