/**
 * Android navigation-bar icons: expo-router's Compose toolbar draws an image
 * source, not an SF Symbol name. Every semantic `IconName` maps to the vector
 * drawable of its Material Symbol (assets/icons/android, generated from the
 * font expo-symbols draws in-content icons with by `scripts/android-icons.py`),
 * so toolbar and content icons match. The table is generated from
 * src/ui/core.tsx `ICONS`: re-run `scripts/android-icons.py` after adding one.
 */
import type { ImageSourcePropType } from 'react-native';
import type { IconName } from './core';

/* eslint-disable @typescript-eslint/no-require-imports -- static asset table */
const SOURCES: Record<IconName, ImageSourcePropType> = {
  plus: require('../../assets/icons/android/add.xml'),
  up: require('../../assets/icons/android/arrow_upward.xml'),
  stop: require('../../assets/icons/android/stop.xml'),
  search: require('../../assets/icons/android/search.xml'),
  chevR: require('../../assets/icons/android/chevron_right.xml'),
  chevD: require('../../assets/icons/android/expand_more.xml'),
  chevUpDown: require('../../assets/icons/android/unfold_more.xml'),
  check: require('../../assets/icons/android/check.xml'),
  x: require('../../assets/icons/android/close.xml'),
  book: require('../../assets/icons/android/menu_book.xml'),
  books: require('../../assets/icons/android/menu_book.xml'),
  globe: require('../../assets/icons/android/public.xml'),
  lock: require('../../assets/icons/android/lock.xml'),
  file: require('../../assets/icons/android/description.xml'),
  bar: require('../../assets/icons/android/bar_chart.xml'),
  checkCircle: require('../../assets/icons/android/check_circle.xml'),
  checkCircleFill: require('../../assets/icons/android/check_circle.xml'),
  pen: require('../../assets/icons/android/edit.xml'),
  compose: require('../../assets/icons/android/edit_square.xml'),
  copy: require('../../assets/icons/android/content_copy.xml'),
  refresh: require('../../assets/icons/android/refresh.xml'),
  share: require('../../assets/icons/android/share.xml'),
  sparkle: require('../../assets/icons/android/auto_awesome.xml'),
  brain: require('../../assets/icons/android/psychology.xml'),
  msg: require('../../assets/icons/android/chat_bubble.xml'),
  msgs: require('../../assets/icons/android/forum.xml'),
  folder: require('../../assets/icons/android/folder.xml'),
  gear: require('../../assets/icons/android/settings.xml'),
  menu: require('../../assets/icons/android/menu.xml'),
  expand: require('../../assets/icons/android/open_in_full.xml'),
  rotate: require('../../assets/icons/android/undo.xml'),
  clock: require('../../assets/icons/android/schedule.xml'),
  camera: require('../../assets/icons/android/photo_camera.xml'),
  image: require('../../assets/icons/android/image.xml'),
  photos: require('../../assets/icons/android/image.xml'),
  arrowDown: require('../../assets/icons/android/arrow_downward.xml'),
  quote: require('../../assets/icons/android/format_quote.xml'),
  tag: require('../../assets/icons/android/sell.xml'),
  tags: require('../../assets/icons/android/label.xml'),
  trash: require('../../assets/icons/android/delete.xml'),
  alert: require('../../assets/icons/android/warning.xml'),
  archive: require('../../assets/icons/android/archive.xml'),
  download: require('../../assets/icons/android/download.xml'),
  list: require('../../assets/icons/android/list.xml'),
  board: require('../../assets/icons/android/view_column.xml'),
  gantt: require('../../assets/icons/android/view_timeline.xml'),
  calendar: require('../../assets/icons/android/calendar_today.xml'),
  users: require('../../assets/icons/android/group.xml'),
  userPlus: require('../../assets/icons/android/person_add.xml'),
  person: require('../../assets/icons/android/account_circle.xml'),
  diamond: require('../../assets/icons/android/diamond.xml'),
  activity: require('../../assets/icons/android/history.xml'),
  foldAll: require('../../assets/icons/android/unfold_less.xml'),
  circle: require('../../assets/icons/android/circle.xml'),
  eye: require('../../assets/icons/android/visibility.xml'),
  flag: require('../../assets/icons/android/flag.xml'),
  filter: require('../../assets/icons/android/filter_list.xml'),
  filterOn: require('../../assets/icons/android/filter_alt.xml'),
  more: require('../../assets/icons/android/more_vert.xml'),
  link: require('../../assets/icons/android/link.xml'),
  server: require('../../assets/icons/android/dns.xml'),
  logout: require('../../assets/icons/android/logout.xml'),
  open: require('../../assets/icons/android/open_in_new.xml'),
  table: require('../../assets/icons/android/table.xml'),
  wrench: require('../../assets/icons/android/build.xml'),
  person2: require('../../assets/icons/android/person.xml'),
  statusProgress: require('../../assets/icons/android/contrast.xml'),
  statusReview: require('../../assets/icons/android/rate_review.xml'),
  statusCancelled: require('../../assets/icons/android/cancel.xml'),
  diamondFill: require('../../assets/icons/android/diamond.xml'),
  flagFill: require('../../assets/icons/android/flag.xml'),
  subtask: require('../../assets/icons/android/subdirectory_arrow_right.xml'),
  personMinus: require('../../assets/icons/android/person_remove.xml'),
  crown: require('../../assets/icons/android/workspace_premium.xml'),
  comment: require('../../assets/icons/android/comment.xml'),
  folderPlus: require('../../assets/icons/android/create_new_folder.xml'),
  plusCircle: require('../../assets/icons/android/add_circle.xml'),
  checklist: require('../../assets/icons/android/checklist.xml'),
  hourglass: require('../../assets/icons/android/hourglass_empty.xml'),
  send: require('../../assets/icons/android/send.xml'),
  form: require('../../assets/icons/android/assignment.xml'),
  branch: require('../../assets/icons/android/call_split.xml'),
  code: require('../../assets/icons/android/code.xml'),
  diagram: require('../../assets/icons/android/account_tree.xml'),
  attach: require('../../assets/icons/android/attach_file.xml'),
  radioOn: require('../../assets/icons/android/radio_button_checked.xml'),
  radioOff: require('../../assets/icons/android/radio_button_unchecked.xml'),
  checkboxOn: require('../../assets/icons/android/check_box.xml'),
  checkboxOff: require('../../assets/icons/android/check_box_outline_blank.xml'),
  pin: require('../../assets/icons/android/push_pin.xml'),
  stopCircle: require('../../assets/icons/android/stop_circle.xml'),
  hand: require('../../assets/icons/android/front_hand.xml'),
  shieldCheck: require('../../assets/icons/android/verified_user.xml'),
  shieldAlert: require('../../assets/icons/android/gpp_maybe.xml'),
  key: require('../../assets/icons/android/key.xml'),
  unlock: require('../../assets/icons/android/lock_open.xml'),
  sleep: require('../../assets/icons/android/bedtime.xml'),
  at: require('../../assets/icons/android/alternate_email.xml'),
  alertCircle: require('../../assets/icons/android/error.xml'),
};
/* eslint-enable @typescript-eslint/no-require-imports */

export function toolbarIcon(name: IconName): ImageSourcePropType {
  return SOURCES[name];
}

/** A bar's overflow menu and its actions in platform order — Android: `⋮` ends the bar (Material). */
export function overflowLast<T>(overflow: T, ...actions: T[]): T[] {
  return [...actions, overflow];
}
