/**
 * Centralized icon mappings using Lucide React.
 *
 * All icons used across the app are exported from here.
 * Import individual icons or use the category/action maps.
 */

import { registeredToolIcon } from './extension-registries';
import {
  MessageCircle,
  BookOpen,
  Library,
  FlaskConical,
  Mail,
  Bot,
  BarChart3,
  RefreshCw,
  User,
  Users,
  Pencil,
  Pen,
  Eraser,
  Type,
  Undo2,
  ArrowUpRight,
  Code2,
  Key,
  Ban,
  Check,
  CheckCircle,
  X,
  XCircle,
  Trash2,
  Package,
  Truck,
  Sprout,
  HelpCircle,
  FileEdit,
  FileText,
  Search,
  MessageSquare,
  MessageSquareWarning,
  ClipboardList,
  Award,
  AppWindow,
  Globe,
  Paperclip,
  Image,
  DollarSign,
  Settings,
  Star,
  ThumbsUp,
  ThumbsDown,
  TrendingUp,
  Lightbulb,
  Link,
  Smartphone,
  Save,
  Brain,
  AlertTriangle,
  Files,
  LogOut,
  Square,
  Plus,
  Clock,
  ChevronRight,
  ChevronLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  ChevronDown,
  ChevronUp,
  CornerDownRight,
  Menu,
  Maximize2,
  ZoomIn,
  ZoomOut,
  Copy,
  Send,
  CircleStop,
  Eye,
  EyeOff,
  History,
  Archive,
  RotateCcw,
  Bookmark,
  Play,
  Pause,
  Download,
  Upload,
  Filter,
  MoreHorizontal,
  Info,
  Wrench,
  StickyNote,
  SlidersHorizontal,
  CircleDot,
  Minus,
  Inbox,
  Sparkles,
  Timer,
  ArrowDownToLine,
  ArrowUpToLine,
  Coins,
  BookOpenCheck,
  ShieldAlert,
  CircleAlert,
  Gauge,
  SquareX,
  ExternalLink,
  Share2,
  Zap,
  FolderKanban,
  Bold,
  Italic,
  Heading1,
  Heading2,
  List,
  ListOrdered,
  Undo,
  Redo,
  LayoutGrid,
  LayoutDashboard,
  GanttChart,
  Tag,
  ArrowLeft,
  CheckCircle2,
  Loader,
  Circle,
  Edit3,
  Calendar,
  House,
  GripVertical,
  Map,
  ListChecks,
  ArrowRight,
  Wifi,
  Shield,
  ArrowUp,
  Palette,
  Sun,
  Moon,
  AtSign,
  MessageSquareQuote,
  ArrowUpDown,
  Code,
  Braces,
  FileDown,
  FileUp,
  CheckSquare,
  Bug,
  Lock,
  Keyboard,
  Server,
  ShieldCheck,
  Monitor,
  MonitorDown,
  FolderOpen,
  Folder,
  FolderPlus,
  ScrollText,
  Cpu,
  Heart,
  Layers,
  WifiOff,
  Loader2,
  ArrowDown,
  FileSearch,
  Cloud,
  LogIn,
  Calculator,
  Pin,
  PinOff,
  Building2,
  Megaphone,
  ListTodo,
  UserPlus,
  GitFork,
  GitBranch,
  Plug,
  Unplug,
  Signal,
  Radio,
  Video,
  Minimize2,
  BookPlus,
  Crown,
  HardHat,
  GraduationCap,
  Headphones,
  Glasses,
  HatGlasses,
  Coffee,
  Droplets,
  BriefcaseBusiness,
  CheckCheck,
  Table2,
  Columns3,
  Workflow,
  Flag,
  type LucideIcon,
} from 'lucide-react';

// Re-export for direct usage
export {
  MessageCircle,
  BookOpen,
  Library,
  FlaskConical,
  Mail,
  Bot,
  BarChart3,
  RefreshCw,
  User,
  Users,
  Pencil,
  Pen,
  Eraser,
  Type,
  Undo2,
  ArrowUpRight,
  Code2,
  Key,
  Ban,
  Check,
  CheckCircle,
  X,
  XCircle,
  Trash2,
  Package,
  Truck,
  Sprout,
  HelpCircle,
  FileEdit,
  FileText,
  Search,
  MessageSquare,
  MessageSquareWarning,
  ClipboardList,
  Award,
  AppWindow,
  Globe,
  Paperclip,
  Image,
  DollarSign,
  Settings,
  Star,
  ThumbsUp,
  ThumbsDown,
  TrendingUp,
  Lightbulb,
  Link,
  Smartphone,
  Save,
  Brain,
  AlertTriangle,
  Files,
  LogOut,
  Square,
  Plus,
  Clock,
  ChevronRight,
  ChevronLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  ChevronDown,
  ChevronUp,
  CornerDownRight,
  Menu,
  Maximize2,
  ZoomIn,
  ZoomOut,
  Copy,
  Send,
  CircleStop,
  Eye,
  EyeOff,
  History,
  Archive,
  RotateCcw,
  Bookmark,
  Play,
  Pause,
  Download,
  Upload,
  Filter,
  MoreHorizontal,
  Info,
  Wrench,
  StickyNote,
  SlidersHorizontal,
  CircleDot,
  Minus,
  Inbox,
  Sparkles,
  Timer,
  ArrowDownToLine,
  ArrowUpToLine,
  Coins,
  BookOpenCheck,
  ShieldAlert,
  CircleAlert,
  Gauge,
  SquareX,
  ExternalLink,
  Share2,
  Zap,
  FolderKanban,
  Bold,
  Italic,
  Heading1,
  Heading2,
  List,
  ListOrdered,
  Undo,
  Redo,
  LayoutGrid,
  LayoutDashboard,
  GanttChart,
  Tag,
  ArrowLeft,
  CheckCircle2,
  Loader,
  Circle,
  Edit3,
  Calendar,
  House,
  GripVertical,
  Map,
  ListChecks,
  ArrowRight,
  Wifi,
  Shield,
  Crown,
  HardHat,
  GraduationCap,
  Headphones,
  Glasses,
  HatGlasses,
  Coffee,
  Droplets,
  BriefcaseBusiness,
  ArrowUp,
  Palette,
  Sun,
  Moon,
  AtSign,
  MessageSquareQuote,
  ArrowUpDown,
  Code,
  Braces,
  FileDown,
  FileUp,
  CheckSquare,
  Bug,
  Lock,
  Keyboard,
  Server,
  ShieldCheck,
  Monitor,
  MonitorDown,
  FolderOpen,
  Folder,
  FolderPlus,
  ScrollText,
  Cpu,
  Heart,
  Layers,
  WifiOff,
  Loader2,
  ArrowDown,
  FileSearch,
  Cloud,
  LogIn,
  Calculator,
  Pin,
  PinOff,
  Building2,
  Megaphone,
  ListTodo,
  UserPlus,
  GitFork,
  GitBranch,
  Plug,
  Unplug,
  Signal,
  Radio,
  Video,
  Minimize2,
  BookPlus,
  CheckCheck,
  Table2,
  Columns3,
  Workflow,
  Flag,
};
export type { LucideIcon };

// ─── Content Category Icons ──────────────────────────────

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  product: Package,
  plant: Sprout,
  faq: HelpCircle,
  blog: FileEdit,
  topic: Files,
};

/** Get the Lucide icon for a content category. */
export function getCategoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category] || FileText;
}

// ─── Context Type Icons ─────────────────────────────────

export const CONTEXT_ICONS: Record<string, LucideIcon> = {
  'wiki-detail': FileText,
  'wiki-list': BookOpen,
  chat: MessageCircle,
  eval: FlaskConical,
  dashboard: LayoutDashboard,
};

/** Get the Lucide icon for a page context type. */
export function getContextIcon(type: string): LucideIcon {
  return CONTEXT_ICONS[type] || FileText;
}

// ─── Tool Icons ─────────────────────────────────────────

export const TOOL_ICONS: Record<string, LucideIcon> = {
  search: Search,
  get_page: FileText,
  eval_message: FlaskConical,
  manage_eval_dataset: FileEdit,
  analyze_image: Image,
  query_eval_runs: BarChart3,
  external_search: Globe,
  ask_user: ClipboardList,
  feature_request: Lightbulb,
  generate_image: Palette,
  project_manager: FolderKanban,
  knowledge_query: BookOpen,

  compute: Calculator,
  skill_query: Package,
  skill_mutation: Upload,
  tables_query: Table2,
  tables_mutation: Table2,
  tables_schema_plan: Columns3,
};

/** Get the Lucide icon for a tool name. */
export function getToolIcon(toolName: string): LucideIcon {
  return registeredToolIcon(toolName) || TOOL_ICONS[toolName] || Wrench;
}

// ─── Tool Brief Descriptions ─────────────────────────────

export const TOOL_BRIEFS: Record<string, string> = {
  search: 'Search knowledge base for products, guides & troubleshooting',
  get_page: 'Read a specific wiki page in detail',
  analyze_image: 'Extract important information from images',
  external_search: 'Search the internet for latest information',
  eval_message: 'Evaluate chat response quality & accuracy',
  manage_eval_dataset: 'Manage evaluation test datasets',
  query_eval_runs: 'Query and analyze evaluation run results',
  ask_user: 'Ask the user clarifying questions',
  feature_request: 'Submit and manage feature requests',
  generate_image: 'Generate images from text descriptions',
  project_manager: 'Create and manage projects & tasks',
  knowledge_query: 'Browse, search and read team, personal and shared knowledge',
  compute: 'Execute code for precise data analysis & calculations',
  tables_query: 'Inspect schemas, query records, and aggregate internal Tables',
  tables_mutation: 'Create, update, upsert, and delete Tables records',
  tables_schema_plan: 'Draft Base, table and field changes for you to confirm',
};

/** Get brief description for a tool. */
export function getToolBrief(toolName: string): string {
  return TOOL_BRIEFS[toolName] || toolName;
}
