/**
 * Knowledge application manifest.
 */

import { compileApp, defineApp } from '@greenhouse/platform-kernel';

export const knowledgeManifest = compileApp(
  defineApp({
    id: 'knowledge',
    version: '1.0.1',
    title: 'Knowledge',
    description: 'Team and personal knowledge documents, versions, sharing, and AI-assisted editing.',
    modules: {
      library: {
        title: 'Knowledge library',
        description: 'Documents, search, and version history.',
        icon: 'BookOpen',
      },
      collaboration: {
        title: 'Sharing',
        description: 'User and group sharing for private documents.',
        icon: 'Share2',
      },
      intelligence: {
        title: 'AI assistance',
        description: 'Draft, rewrite, and enrich knowledge documents.',
        icon: 'Sparkles',
      },
    },
    entities: {
      document: {
        title: 'Knowledge document',
        module: 'library',
        table: 'knowledge_base',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          slug: { kind: 'text', title: 'Slug', required: true, unique: true, searchable: true },
          title: { kind: 'text', title: 'Title', required: true, searchable: true, sortable: true },
          content: { kind: 'longText', title: 'Markdown', required: true, searchable: true },
          contentJson: { kind: 'json', title: 'Editor document', classification: 'internal' },
          summary: { kind: 'longText', title: 'Summary', searchable: true },
          questions: { kind: 'json', title: 'Questions', searchable: true },
          topics: { kind: 'json', title: 'Topics', filterable: true },
          tags: { kind: 'json', title: 'Tags', filterable: true },
          visibility: {
            kind: 'enum',
            title: 'Visibility',
            required: true,
            filterable: true,
            values: ['team', 'private'],
          },
          status: {
            kind: 'enum',
            title: 'Status',
            required: true,
            filterable: true,
            values: ['draft', 'published', 'archived'],
          },
          ownerUserId: { kind: 'user', title: 'Owner', filterable: true },
          createdBy: { kind: 'user', title: 'Created by', classification: 'internal' },
          updatedBy: { kind: 'user', title: 'Updated by', classification: 'internal' },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
          updatedAt: { kind: 'dateTime', title: 'Updated at', sortable: true, classification: 'internal' },
        },
      },
      version: {
        title: 'Document version',
        module: 'library',
        table: 'knowledge_base_versions',
        accessScopes: ['collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          documentId: { kind: 'relation', title: 'Document', target: 'document', required: true },
          version: { kind: 'integer', title: 'Version', required: true, sortable: true },
          title: { kind: 'text', title: 'Title', required: true },
          content: { kind: 'longText', title: 'Markdown', required: true },
          changedBy: { kind: 'user', title: 'Changed by', classification: 'internal' },
          changeReason: { kind: 'text', title: 'Reason' },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
        },
      },
      share: {
        title: 'Knowledge share',
        module: 'collaboration',
        table: 'knowledge_base_shares',
        accessScopes: ['own', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          documentId: { kind: 'relation', title: 'Document', target: 'document', required: true },
          sharedWith: { kind: 'text', title: 'User or group', required: true, classification: 'confidential' },
          role: {
            kind: 'enum',
            title: 'Role',
            required: true,
            values: ['reader', 'editor'],
          },
          sharedBy: { kind: 'user', title: 'Shared by', classification: 'internal' },
          message: { kind: 'longText', title: 'Message', classification: 'confidential' },
          createdAt: { kind: 'dateTime', title: 'Created at', classification: 'internal' },
        },
      },
    },
    actions: {
      listDocuments: {
        title: 'List documents',
        module: 'library',
        entity: 'document',
        kind: 'query',
        capability: 'knowledge.library.read',
        risk: 'read',
        mcp: true,
      },
      readDocument: {
        title: 'Read document',
        module: 'library',
        entity: 'document',
        kind: 'query',
        capability: 'knowledge.library.read',
        risk: 'read',
        mcp: true,
      },
      searchDocuments: {
        title: 'Search documents',
        module: 'library',
        entity: 'document',
        kind: 'query',
        capability: 'knowledge.library.read',
        risk: 'read',
        mcp: true,
      },
      listVersions: {
        title: 'List versions',
        module: 'library',
        entity: 'version',
        kind: 'query',
        capability: 'knowledge.library.read',
        risk: 'read',
        mcp: true,
      },
      createDocument: {
        title: 'Create document',
        module: 'library',
        entity: 'document',
        kind: 'command',
        capability: 'knowledge.library.create',
        risk: 'medium',
        mcp: true,
      },
      updateDocument: {
        title: 'Update document',
        module: 'library',
        entity: 'document',
        kind: 'command',
        capability: 'knowledge.library.update',
        risk: 'medium',
        mcp: true,
      },
      archiveDocument: {
        title: 'Archive document',
        module: 'library',
        entity: 'document',
        kind: 'command',
        capability: 'knowledge.library.archive',
        risk: 'high',
        mcp: true,
      },
      restoreVersion: {
        title: 'Restore document version',
        module: 'library',
        entity: 'version',
        kind: 'command',
        capability: 'knowledge.library.update',
        risk: 'high',
        mcp: true,
      },
      listShares: {
        title: 'List document shares',
        module: 'collaboration',
        entity: 'share',
        kind: 'query',
        capability: 'knowledge.collaboration.read',
        risk: 'read',
      },
      manageShares: {
        title: 'Manage document shares',
        module: 'collaboration',
        entity: 'share',
        kind: 'command',
        capability: 'knowledge.collaboration.manage',
        risk: 'high',
        mcp: true,
      },
      generateDocument: {
        title: 'Generate document draft',
        module: 'intelligence',
        kind: 'command',
        capability: 'knowledge.intelligence.generate',
        risk: 'medium',
      },
      rewriteDocument: {
        title: 'Rewrite document',
        module: 'intelligence',
        kind: 'command',
        capability: 'knowledge.intelligence.generate',
        risk: 'medium',
      },
      enrichDocument: {
        title: 'Enrich document',
        module: 'intelligence',
        kind: 'command',
        capability: 'knowledge.intelligence.generate',
        risk: 'medium',
      },
    },
    forms: {
      documentEdit: {
        title: 'Knowledge document',
        entity: 'document',
        mode: 'edit',
        sections: [
          {
            id: 'main',
            columns: 2,
            fields: [
              { field: 'title', span: 2 },
              { field: 'content', span: 2, component: 'textarea' },
              { field: 'visibility', component: 'select' },
              { field: 'status', component: 'select' },
              { field: 'tags', span: 2 },
            ],
          },
        ],
      },
    },
    views: {
      documentList: {
        title: 'Knowledge documents',
        entity: 'document',
        type: 'table',
        fields: ['title', 'visibility', 'status', 'ownerUserId', 'updatedAt'],
        searchableFields: ['title', 'content', 'summary'],
        filterableFields: ['visibility', 'status', 'ownerUserId', 'tags'],
        defaultSort: [{ field: 'updatedAt', direction: 'desc' }],
      },
    },
    navigation: [
      {
        id: 'knowledge',
        title: 'Knowledge',
        module: 'library',
        path: '/knowledge',
        view: 'documentList',
        capability: 'knowledge.library.read',
      },
    ],
  }),
);
