/**
 * Projects application manifest.
 *
 * This is the declarative, persisted catalog for the existing Projects domain.
 * It contains no handlers or database references; runtime behavior lives in
 * ../projects/application.ts.
 */

import { compileApp, defineApp } from '@greenhouse/platform-kernel';

export const projectsManifest = compileApp(
  defineApp({
    id: 'projects',
    version: '1.0.1',
    title: 'Projects',
    description: 'Team projects, tasks, collaboration, and activity history.',
    modules: {
      portfolio: {
        title: 'Projects',
        description: 'Project portfolio and planning.',
        icon: 'FolderKanban',
      },
      execution: {
        title: 'Tasks',
        description: 'Task planning and delivery.',
        icon: 'ListTodo',
      },
      collaboration: {
        title: 'Collaboration',
        description: 'Members, comments, and activity.',
        icon: 'Users',
      },
    },
    entities: {
      project: {
        title: 'Project',
        module: 'portfolio',
        table: 'projects',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          title: { kind: 'text', title: 'Title', required: true, searchable: true, sortable: true },
          description: { kind: 'longText', title: 'Description', searchable: true },
          status: {
            kind: 'enum',
            title: 'Status',
            required: true,
            filterable: true,
            sortable: true,
            values: ['planning', 'active', 'on_hold', 'completed', 'archived'],
          },
          priority: {
            kind: 'enum',
            title: 'Priority',
            required: true,
            filterable: true,
            values: ['low', 'normal', 'high', 'urgent'],
          },
          ownerId: { kind: 'user', title: 'Owner', required: true, filterable: true },
          visibility: {
            kind: 'enum',
            title: 'Visibility',
            required: true,
            filterable: true,
            values: ['public', 'private'],
          },
          startDate: { kind: 'date', title: 'Start date', sortable: true },
          endDate: { kind: 'date', title: 'End date', sortable: true },
          color: { kind: 'text', title: 'Color' },
          createdBy: { kind: 'user', title: 'Created by', classification: 'internal' },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
          updatedAt: { kind: 'dateTime', title: 'Updated at', sortable: true, classification: 'internal' },
        },
      },
      task: {
        title: 'Task',
        module: 'execution',
        table: 'tasks',
        accessScopes: ['own', 'collaborating', 'assigned', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          projectId: { kind: 'relation', title: 'Project', target: 'project', required: true },
          parentId: { kind: 'relation', title: 'Parent task', target: 'task' },
          title: { kind: 'text', title: 'Title', required: true, searchable: true, sortable: true },
          description: { kind: 'longText', title: 'Description', searchable: true },
          status: {
            kind: 'enum',
            title: 'Status',
            required: true,
            filterable: true,
            values: ['todo', 'in_progress', 'in_review', 'done', 'cancelled'],
          },
          priority: {
            kind: 'enum',
            title: 'Priority',
            required: true,
            filterable: true,
            values: ['low', 'normal', 'high', 'urgent'],
          },
          assigneeId: { kind: 'user', title: 'Assignee', filterable: true },
          startDate: { kind: 'date', title: 'Start date', sortable: true },
          dueDate: { kind: 'date', title: 'Due date', sortable: true },
          tags: { kind: 'json', title: 'Tags', filterable: true },
          dependencies: { kind: 'relations', title: 'Dependencies', target: 'task' },
          createdBy: { kind: 'user', title: 'Created by', classification: 'internal' },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
          updatedAt: { kind: 'dateTime', title: 'Updated at', sortable: true, classification: 'internal' },
        },
      },
      comment: {
        title: 'Task comment',
        module: 'collaboration',
        table: 'task_comments',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          taskId: { kind: 'relation', title: 'Task', target: 'task', required: true },
          userId: { kind: 'user', title: 'Author', required: true },
          content: { kind: 'longText', title: 'Content', required: true },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
        },
      },
      member: {
        title: 'Project member',
        module: 'collaboration',
        table: 'project_members',
        accessScopes: ['collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          projectId: { kind: 'relation', title: 'Project', target: 'project', required: true },
          userId: { kind: 'user', title: 'User', required: true },
          role: {
            kind: 'enum',
            title: 'Role',
            required: true,
            values: ['owner', 'member'],
          },
          addedBy: { kind: 'user', title: 'Added by', classification: 'internal' },
          createdAt: { kind: 'dateTime', title: 'Created at', classification: 'internal' },
        },
      },
      activity: {
        title: 'Project activity',
        module: 'collaboration',
        table: 'project_activities',
        accessScopes: ['collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          projectId: { kind: 'relation', title: 'Project', target: 'project', required: true },
          taskId: { kind: 'relation', title: 'Task', target: 'task' },
          userId: { kind: 'user', title: 'User', required: true },
          action: { kind: 'text', title: 'Action', required: true },
          detail: { kind: 'longText', title: 'Detail' },
          createdAt: { kind: 'dateTime', title: 'Created at', sortable: true, classification: 'internal' },
        },
      },
    },
    actions: {
      listProjects: {
        title: 'List projects',
        module: 'portfolio',
        entity: 'project',
        kind: 'query',
        capability: 'projects.portfolio.read',
        risk: 'read',
        mcp: true,
      },
      getProject: {
        title: 'Read project',
        module: 'portfolio',
        entity: 'project',
        kind: 'query',
        capability: 'projects.portfolio.read',
        risk: 'read',
        mcp: true,
      },
      getGantt: {
        title: 'Read project timeline',
        module: 'portfolio',
        entity: 'project',
        kind: 'query',
        capability: 'projects.portfolio.read',
        risk: 'read',
      },
      createProject: {
        title: 'Create project',
        module: 'portfolio',
        entity: 'project',
        kind: 'command',
        capability: 'projects.portfolio.create',
        risk: 'medium',
        mcp: true,
      },
      updateProject: {
        title: 'Update project',
        module: 'portfolio',
        entity: 'project',
        kind: 'command',
        capability: 'projects.portfolio.update',
        risk: 'medium',
        mcp: true,
      },
      deleteProject: {
        title: 'Delete project',
        module: 'portfolio',
        entity: 'project',
        kind: 'command',
        capability: 'projects.portfolio.delete',
        risk: 'destructive',
      },
      listTasks: {
        title: 'List tasks',
        module: 'execution',
        entity: 'task',
        kind: 'query',
        capability: 'projects.execution.read',
        risk: 'read',
        mcp: true,
      },
      createTask: {
        title: 'Create task',
        module: 'execution',
        entity: 'task',
        kind: 'command',
        capability: 'projects.execution.create',
        risk: 'medium',
        mcp: true,
      },
      updateTask: {
        title: 'Update task',
        module: 'execution',
        entity: 'task',
        kind: 'command',
        capability: 'projects.execution.update',
        risk: 'medium',
        mcp: true,
      },
      deleteTask: {
        title: 'Delete task',
        module: 'execution',
        entity: 'task',
        kind: 'command',
        capability: 'projects.execution.delete',
        risk: 'high',
      },
      reorderTasks: {
        title: 'Reorder tasks',
        module: 'execution',
        entity: 'task',
        kind: 'command',
        capability: 'projects.execution.update',
        risk: 'medium',
      },
      moveTask: {
        title: 'Move task',
        module: 'execution',
        entity: 'task',
        kind: 'command',
        capability: 'projects.execution.update',
        risk: 'medium',
      },
      listComments: {
        title: 'List comments',
        module: 'collaboration',
        entity: 'comment',
        kind: 'query',
        capability: 'projects.collaboration.read',
        risk: 'read',
      },
      addComment: {
        title: 'Add comment',
        module: 'collaboration',
        entity: 'comment',
        kind: 'command',
        capability: 'projects.collaboration.create',
        risk: 'low',
      },
      deleteComment: {
        title: 'Delete comment',
        module: 'collaboration',
        entity: 'comment',
        kind: 'command',
        capability: 'projects.collaboration.delete',
        risk: 'high',
      },
      listActivities: {
        title: 'List activity',
        module: 'collaboration',
        entity: 'activity',
        kind: 'query',
        capability: 'projects.collaboration.read',
        risk: 'read',
      },
      listMembers: {
        title: 'List project members',
        module: 'collaboration',
        entity: 'member',
        kind: 'query',
        capability: 'projects.collaboration.read',
        risk: 'read',
      },
      manageMembers: {
        title: 'Manage project members',
        module: 'collaboration',
        entity: 'member',
        kind: 'command',
        capability: 'projects.collaboration.manage',
        risk: 'high',
      },
      listAssignableUsers: {
        title: 'List assignable users',
        module: 'collaboration',
        entity: 'member',
        kind: 'query',
        capability: 'projects.collaboration.assign',
        risk: 'read',
      },
    },
    forms: {
      projectCreate: {
        title: 'Create project',
        entity: 'project',
        mode: 'create',
        sections: [
          {
            id: 'main',
            columns: 2,
            fields: [
              { field: 'title', span: 2 },
              { field: 'description', span: 2, component: 'textarea' },
              { field: 'status', component: 'select' },
              { field: 'priority', component: 'select' },
              { field: 'ownerId', component: 'userSelect' },
              { field: 'visibility', component: 'select' },
              { field: 'startDate' },
              { field: 'endDate' },
            ],
          },
        ],
      },
    },
    views: {
      projectList: {
        title: 'Projects',
        entity: 'project',
        type: 'table',
        fields: ['title', 'status', 'priority', 'ownerId', 'startDate', 'endDate'],
        searchableFields: ['title', 'description'],
        filterableFields: ['status', 'priority', 'ownerId', 'visibility'],
        defaultSort: [{ field: 'updatedAt', direction: 'desc' }],
      },
      taskBoard: {
        title: 'Task board',
        entity: 'task',
        type: 'kanban',
        fields: ['title', 'status', 'priority', 'assigneeId', 'dueDate'],
        filterableFields: ['status', 'priority', 'assigneeId'],
        groupBy: 'status',
      },
    },
    navigation: [
      {
        id: 'projects',
        title: 'Projects',
        module: 'portfolio',
        path: '/projects',
        view: 'projectList',
        capability: 'projects.portfolio.read',
      },
      {
        id: 'projectGantt',
        title: 'Timeline',
        module: 'execution',
        path: '/projects/gantt',
        capability: 'projects.execution.read',
      },
    ],
  }),
);
