/**
 * Tables application manifest.
 *
 * User-created Base/Table/Field metadata remains business data. This manifest
 * only declares the stable application entities/actions shared by every
 * transport and never contains dynamic user schema.
 */

import { compileApp, defineApp } from '@greenhouse/platform-kernel';

export const tablesManifest = compileApp(
  defineApp({
    id: 'tables',
    version: '1.2.1',
    title: 'Tables',
    description: 'Internal multidimensional tables, shared grid views, records, and lightweight dashboards.',
    modules: {
      structure: {
        title: 'Structure',
        description: 'Bases, tables, fields, members, and views.',
        icon: 'Table2',
      },
      data: {
        title: 'Records',
        description: 'Validated dynamic records and bounded queries.',
        icon: 'Rows3',
      },
      analytics: {
        title: 'Dashboards',
        description: 'Server-side aggregates and dashboard widgets.',
        icon: 'ChartNoAxesCombined',
      },
    },
    entities: {
      base: {
        title: 'Base',
        module: 'structure',
        table: 'table_bases',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          name: { kind: 'text', title: 'Name', required: true, searchable: true, sortable: true },
          description: { kind: 'longText', title: 'Description', searchable: true },
          visibility: { kind: 'enum', title: 'Visibility', values: ['private', 'team'], filterable: true },
          ownerId: { kind: 'user', title: 'Owner', required: true, filterable: true },
          createdAt: { kind: 'dateTime', title: 'Created at', classification: 'internal' },
          updatedAt: { kind: 'dateTime', title: 'Updated at', classification: 'internal' },
        },
      },
      table: {
        title: 'Table',
        module: 'structure',
        table: 'table_tables',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          baseId: { kind: 'relation', title: 'Base', target: 'base', required: true },
          name: { kind: 'text', title: 'Name', required: true, searchable: true },
          description: { kind: 'longText', title: 'Description' },
          position: { kind: 'integer', title: 'Position', sortable: true },
          schemaRevision: { kind: 'integer', title: 'Schema revision', classification: 'internal' },
        },
      },
      field: {
        title: 'Field',
        module: 'structure',
        table: 'table_fields',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          tableId: { kind: 'relation', title: 'Table', target: 'table', required: true },
          name: { kind: 'text', title: 'Name', required: true },
          type: { kind: 'text', title: 'Type', required: true, filterable: true },
          required: { kind: 'boolean', title: 'Required' },
          primary: { kind: 'boolean', title: 'Primary' },
          config: { kind: 'json', title: 'Configuration', classification: 'internal' },
        },
      },
      view: {
        title: 'View',
        module: 'structure',
        table: 'table_views',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          tableId: { kind: 'relation', title: 'Table', target: 'table', required: true },
          name: { kind: 'text', title: 'Name', required: true },
          scope: { kind: 'enum', title: 'Scope', values: ['shared', 'personal'], filterable: true },
          ownerId: { kind: 'user', title: 'Owner' },
          config: { kind: 'json', title: 'Configuration', classification: 'internal' },
          revision: { kind: 'integer', title: 'Revision', classification: 'internal' },
        },
      },
      form: {
        title: 'Form',
        module: 'structure',
        table: 'table_forms',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          tableId: { kind: 'relation', title: 'Table', target: 'table', required: true },
          name: { kind: 'text', title: 'Name', required: true },
          status: { kind: 'enum', title: 'Status', values: ['draft', 'published'] },
          config: { kind: 'json', title: 'Configuration', classification: 'internal' },
          revision: { kind: 'integer', title: 'Revision', classification: 'internal' },
        },
      },
      record: {
        title: 'Record',
        module: 'data',
        table: 'table_records',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          tableId: { kind: 'relation', title: 'Table', target: 'table', required: true },
          values: { kind: 'json', title: 'Values', required: true },
          revision: { kind: 'integer', title: 'Revision', required: true, classification: 'internal' },
          createdBy: { kind: 'user', title: 'Created by', classification: 'internal' },
          updatedBy: { kind: 'user', title: 'Updated by', classification: 'internal' },
          createdAt: { kind: 'dateTime', title: 'Created at', classification: 'internal' },
          updatedAt: { kind: 'dateTime', title: 'Updated at', classification: 'internal' },
        },
      },
      dashboard: {
        title: 'Dashboard',
        module: 'analytics',
        table: 'table_dashboards',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          baseId: { kind: 'relation', title: 'Base', target: 'base', required: true },
          name: { kind: 'text', title: 'Name', required: true },
          description: { kind: 'longText', title: 'Description' },
          revision: { kind: 'integer', title: 'Revision', classification: 'internal' },
        },
      },
      dashboardWidget: {
        title: 'Dashboard widget',
        module: 'analytics',
        table: 'table_dashboard_widgets',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          dashboardId: { kind: 'relation', title: 'Dashboard', target: 'dashboard', required: true },
          tableId: { kind: 'relation', title: 'Table', target: 'table' },
          type: { kind: 'text', title: 'Type', required: true },
          title: { kind: 'text', title: 'Title', required: true },
          config: { kind: 'json', title: 'Configuration', classification: 'internal' },
          layout: { kind: 'json', title: 'Layout', classification: 'internal' },
          revision: { kind: 'integer', title: 'Revision', classification: 'internal' },
        },
      },
      automation: {
        title: 'Automation',
        module: 'data',
        table: 'table_automation_rules',
        accessScopes: ['own', 'collaborating', 'all'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          baseId: { kind: 'relation', title: 'Base', target: 'base', required: true },
          tableId: { kind: 'relation', title: 'Table', target: 'table', required: true },
          name: { kind: 'text', title: 'Name', required: true },
          status: { kind: 'enum', title: 'Status', values: ['disabled', 'enabled'] },
          trigger: { kind: 'text', title: 'Trigger', required: true },
          config: { kind: 'json', title: 'Configuration', classification: 'internal' },
          revision: { kind: 'integer', title: 'Revision', classification: 'internal' },
        },
      },
      notification: {
        title: 'Notification',
        module: 'data',
        table: 'table_notifications',
        accessScopes: ['own'],
        fields: {
          id: { kind: 'integer', title: 'ID', classification: 'internal' },
          title: { kind: 'text', title: 'Title', required: true },
          message: { kind: 'longText', title: 'Message', required: true },
          readAt: { kind: 'dateTime', title: 'Read at' },
          createdAt: { kind: 'dateTime', title: 'Created at', classification: 'internal' },
        },
      },
    },
    actions: {
      listBases: {
        title: 'List bases',
        module: 'structure',
        entity: 'base',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
        mcp: true,
      },
      getBase: {
        title: 'Read base',
        module: 'structure',
        entity: 'base',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
        mcp: true,
      },
      createBase: {
        title: 'Create base',
        module: 'structure',
        entity: 'base',
        kind: 'command',
        capability: 'tables.structure.create',
        risk: 'medium',
      },
      updateBase: {
        title: 'Update base',
        module: 'structure',
        entity: 'base',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      archiveBase: {
        title: 'Archive base',
        module: 'structure',
        entity: 'base',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'destructive',
      },
      listMembers: {
        title: 'List base members',
        module: 'structure',
        entity: 'base',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      listBaseAudit: {
        title: 'Read base audit',
        module: 'structure',
        entity: 'base',
        kind: 'query',
        capability: 'tables.structure.audit',
        risk: 'read',
      },
      manageMembers: {
        title: 'Manage base members',
        module: 'structure',
        entity: 'base',
        kind: 'command',
        capability: 'tables.structure.manageMembers',
        risk: 'high',
      },
      listAssignableUsers: {
        title: 'List assignable users',
        module: 'structure',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      listTables: {
        title: 'List tables',
        module: 'structure',
        entity: 'table',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
        mcp: true,
      },
      getSchema: {
        title: 'Read table schema',
        module: 'structure',
        entity: 'table',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
        mcp: true,
      },
      listSchemaVersions: {
        title: 'List table schema versions',
        module: 'structure',
        entity: 'table',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      getSchemaVersion: {
        title: 'Read table schema version',
        module: 'structure',
        entity: 'table',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      createTable: {
        title: 'Create table',
        module: 'structure',
        entity: 'table',
        kind: 'command',
        capability: 'tables.structure.create',
        risk: 'medium',
      },
      updateTable: {
        title: 'Update table',
        module: 'structure',
        entity: 'table',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      archiveTable: {
        title: 'Archive table',
        module: 'structure',
        entity: 'table',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'destructive',
      },
      createField: {
        title: 'Create field',
        module: 'structure',
        entity: 'field',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      updateField: {
        title: 'Update field',
        module: 'structure',
        entity: 'field',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      archiveField: {
        title: 'Archive field',
        module: 'structure',
        entity: 'field',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'high',
      },
      listViews: {
        title: 'List views',
        module: 'structure',
        entity: 'view',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      createView: {
        title: 'Create view',
        module: 'structure',
        entity: 'view',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'low',
      },
      updateView: {
        title: 'Update view',
        module: 'structure',
        entity: 'view',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'low',
      },
      listForms: {
        title: 'List forms',
        module: 'structure',
        entity: 'form',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      getForm: {
        title: 'Read form',
        module: 'structure',
        entity: 'form',
        kind: 'query',
        capability: 'tables.structure.read',
        risk: 'read',
      },
      createForm: {
        title: 'Create form',
        module: 'structure',
        entity: 'form',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      updateForm: {
        title: 'Update form',
        module: 'structure',
        entity: 'form',
        kind: 'command',
        capability: 'tables.structure.update',
        risk: 'medium',
      },
      submitForm: {
        title: 'Submit form',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.create',
        risk: 'medium',
      },
      getRecord: {
        title: 'Read record',
        module: 'data',
        entity: 'record',
        kind: 'query',
        capability: 'tables.data.read',
        risk: 'read',
        mcp: true,
      },
      queryRecords: {
        title: 'Query records',
        module: 'data',
        entity: 'record',
        kind: 'query',
        capability: 'tables.data.read',
        risk: 'read',
        mcp: true,
      },
      aggregateRecords: {
        title: 'Aggregate records',
        module: 'data',
        entity: 'record',
        kind: 'query',
        capability: 'tables.data.read',
        risk: 'read',
        mcp: true,
      },
      createRecord: {
        title: 'Create record',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.create',
        risk: 'medium',
        mcp: true,
      },
      updateRecord: {
        title: 'Update record',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.update',
        risk: 'medium',
        mcp: true,
      },
      batchUpsertRecords: {
        title: 'Batch upsert records',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.update',
        risk: 'medium',
        mcp: true,
      },
      validateBatchRecords: {
        title: 'Validate batch records',
        module: 'data',
        entity: 'record',
        kind: 'query',
        capability: 'tables.data.update',
        risk: 'read',
      },
      deleteRecord: {
        title: 'Delete record',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.delete',
        risk: 'destructive',
        mcp: true,
      },
      listDeletedRecords: {
        title: 'List deleted records',
        module: 'data',
        entity: 'record',
        kind: 'query',
        capability: 'tables.data.delete',
        risk: 'read',
      },
      restoreRecord: {
        title: 'Restore record',
        module: 'data',
        entity: 'record',
        kind: 'command',
        capability: 'tables.data.delete',
        risk: 'medium',
      },
      listAutomations: {
        title: 'List automations',
        module: 'data',
        entity: 'automation',
        kind: 'query',
        capability: 'tables.data.automation',
        risk: 'read',
      },
      createAutomation: {
        title: 'Create automation',
        module: 'data',
        entity: 'automation',
        kind: 'command',
        capability: 'tables.data.automation',
        risk: 'high',
      },
      updateAutomation: {
        title: 'Update automation',
        module: 'data',
        entity: 'automation',
        kind: 'command',
        capability: 'tables.data.automation',
        risk: 'high',
      },
      listAutomationRuns: {
        title: 'List automation runs',
        module: 'data',
        entity: 'automation',
        kind: 'query',
        capability: 'tables.data.automation',
        risk: 'read',
      },
      listNotifications: {
        title: 'List notifications',
        module: 'data',
        entity: 'notification',
        kind: 'query',
        capability: 'tables.data.notifications',
        risk: 'read',
      },
      markNotificationRead: {
        title: 'Mark notification read',
        module: 'data',
        entity: 'notification',
        kind: 'command',
        capability: 'tables.data.notifications',
        risk: 'low',
      },
      listDashboards: {
        title: 'List dashboards',
        module: 'analytics',
        entity: 'dashboard',
        kind: 'query',
        capability: 'tables.analytics.read',
        risk: 'read',
        mcp: true,
      },
      getDashboard: {
        title: 'Read dashboard',
        module: 'analytics',
        entity: 'dashboard',
        kind: 'query',
        capability: 'tables.analytics.read',
        risk: 'read',
        mcp: true,
      },
      createDashboard: {
        title: 'Create dashboard',
        module: 'analytics',
        entity: 'dashboard',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'medium',
      },
      updateDashboard: {
        title: 'Update dashboard',
        module: 'analytics',
        entity: 'dashboard',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'medium',
      },
      deleteDashboard: {
        title: 'Delete dashboard',
        module: 'analytics',
        entity: 'dashboard',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'destructive',
      },
      createDashboardWidget: {
        title: 'Create dashboard widget',
        module: 'analytics',
        entity: 'dashboardWidget',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'medium',
      },
      updateDashboardWidget: {
        title: 'Update dashboard widget',
        module: 'analytics',
        entity: 'dashboardWidget',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'medium',
      },
      deleteDashboardWidget: {
        title: 'Delete dashboard widget',
        module: 'analytics',
        entity: 'dashboardWidget',
        kind: 'command',
        capability: 'tables.analytics.manage',
        risk: 'high',
      },
      queryDashboardWidget: {
        title: 'Query dashboard widget',
        module: 'analytics',
        entity: 'dashboardWidget',
        kind: 'query',
        capability: 'tables.analytics.read',
        risk: 'read',
      },
    },
    navigation: [
      {
        id: 'tablesHome',
        title: 'Tables',
        module: 'structure',
        path: '/tables',
        capability: 'tables.structure.read',
      },
    ],
  }),
);
